### ISSUE TITLE
Prometheus: multiple index nodes: wrong metrics

### ISSUE THREAD

**Issue by davaymne** [graphprotocol/mission-control-indexer#193]
I am running 4 index-nodes and Prometheus configured to collect data from all of them.

- But if deployment is being indexed by node id = index-node-0 (job = index-node-0) then Prometheus returns only one element:  ![screen1](https://user-images.githubusercontent.com/29555611/97650725-4b6ce400-1a52-11eb-85dc-bd071039c502.jpg), 
![screen2](https://user-images.githubusercontent.com/29555611/97653269-47dc5b80-1a58-11eb-919d-976b9157e51a.jpg)

- If deplyment is being indexed by node id = index-node-1 then Prometheus returns 3 elements for 3 x different jobs job = index-node-1, job = index-node-2, job = index-node-3  with the same metric/value ![index-node-1](https://user-images.githubusercontent.com/29555611/97651121-26c53c00-1a53-11eb-82a3-2622080cc3ff.jpg)

- if deployment is being indexed by either node id = index-node-2 or index-node-3 
![grafana](https://user-images.githubusercontent.com/29555611/97651475-15c8fa80-1a54-11eb-8062-46fda90ba383.jpg)
then Prometheus returns empty result 
![index-node-2](https://user-images.githubusercontent.com/29555611/97651415-da2e3080-1a53-11eb-889e-f787bcf7968e.jpg)
.
SW:

- Running docker-compose
image: graphprotocol/graph-node:v0.19.1
- Prometheus config:

```  
  - job_name: 'index-node-0'
    scrape_interval: 5s
    static_configs:
      - targets: ['index-node-0:8040']

  - job_name: 'index-node-1'
    scrape_interval: 5s
    static_configs:
      - targets: ['index-node-1:8040']

  - job_name: 'index-node-2'
    scrape_interval: 5s
    static_configs:
      - targets: ['index-node-1:8040']

  - job_name: 'index-node-3'
    scrape_interval: 5s
    static_configs:
      - targets: ['index-node-1:8040']

```
